apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
   matchLabels:
     app: ubuntu
  template:
    metadata:
      labels:
         app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: library/ubuntu
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;"]